### ISSUE TITLE
频道提审的时候报错

### ISSUE THREAD

**Issue by mas-alone** [nonebot/adapter-qq#120]
配置如下：
```
DRIVER=~httpx+~websockets
QQ_IS_SANDBOX=false
	  "interaction": true,
	  "audio_action": true,
	  "direct_message": true,
	  "c2c_group_at_messages": true
```
类型是公域机器人，提审的时候群聊是正常的可以响应，但是频道(非私聊)就报错。
自己在频道里测试又是正常的。

下面是报错信息：
```
08-13 17:52:14 [WARNING] nonebot | QQ | Failed to parse event Dispatch(opcode=<Opcode.DISPATCH: 0>, data={'author': {'id': '144115219948621845'}, 'channel_id': '1109094', 'content': '<@!这里是botQQ号> /这里是指令名', 'guild_id': '5237615478283154023', 'id': '0887bce886d0f1ff5f10e6d8431a1231343431313532313939343836323138343530c4aeebf4aecece2138b7a0e497e1bbdeee2248cdd9ecb506a0010a', 'mentions': [{'avatar': 'https://bot-resource-1251316161.file.myqcloud.com/avatar/a902988d-e854-4332-9624-7bf2343206309160868616598340570?ts=1706673910', 'bot': True, 'username': '这里是bot名字'}], 'seq': 318312503, 'seq_in_channel': '2512298161850617911', 'timestamp': '2024-08-13T17:52:13+08:00'}, sequence=39, type='AT_MESSAGE_CREATE', id='AT_MESSAGE_CREATE:0887bce886d0f1ff5f10e6d8431a1231343431313532313939343836323138343530c4aeebf4aecece2138b7a0e497e1bbdeee2248cdd9ecb506a0010a')
Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "D:\bot\osubottest\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "D:\bot\osubottest\.venv\lib\site-packages\nonebot\drivers\none.py", line 56, in run
    loop.run_until_complete(self._serve())
  File "D:\Program Files\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Program Files\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\Program Files\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\bot\osubottest\.venv\lib\site-packages\nonebot\adapters\qq\adapter.py", line 180, in _forward_ws
    await self._loop(bot, ws)
> File "D:\bot\osubottest\.venv\lib\site-packages\nonebot\adapters\qq\adapter.py", line 347, in _loop
    event = self.payload_to_event(payload)
  File "D:\bot\osubottest\.venv\lib\site-packages\nonebot\adapters\qq\adapter.py", line 411, in payload_to_event
    return type_validate_python(EventClass, payload.data)
  File "D:\bot\osubottest\.venv\lib\site-packages\nonebot\compat.py", line 372, in type_validate_python
    return parse_obj_as(type_, data)
  File "pydantic\tools.py", line 38, in pydantic.tools.parse_obj_as
    return model_type(__root__=obj).__root__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[AtMessageCreateEvent]
__root__ -> mentions -> 0 -> id
  field required (type=value_error.missing)
```

**Comment by yanyongyu** [comment]
这个报错是QQ提供的字段缺失，该字段是必填字段，请向QQ提issue

**Comment by mas-alone** [comment]
辛苦了，这就close
