### ISSUE TITLE
尝试建立WebSocket连接时，SSL证书验证失败

### ISSUE THREAD

**Issue by chinatsu-yan** [nonebot/adapter-qq#132]
如题，在本地电脑上运行没有问题，但是在服务器上就会这样

```python
11-09 14:35:47 [ERROR] nonebot | QQ | Error while setup websocket to wss://sandbox.api.sgroup.qq.com/websocket. Trying to reconnect...
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "C:\bot\xiaoxi\.venv\lib\site-packages\nonebot\__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "C:\bot\xiaoxi\.venv\lib\site-packages\nonebot\drivers\none.py", line 61, in run
    anyio.run(self._serve)
  File "C:\bot\xiaoxi\.venv\lib\site-packages\anyio\_core\_eventloop.py", line 74, in run
    return async_backend.run(func, args, {}, backend_options)
  File "C:\bot\xiaoxi\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2284, in run
    return runner.run(wrapper())
  File "C:\bot\xiaoxi\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 210, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\bot\xiaoxi\.venv\lib\site-packages\nonebot\adapters\qq\adapter.py", line 154, in _forward_ws
    async with self.websocket(request) as ws:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "C:\bot\xiaoxi\.venv\lib\site-packages\nonebot\internal\adapter\adapter.py", line 99, in websocket
    async with self.driver.websocket(setup) as ws:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "C:\bot\xiaoxi\.venv\lib\site-packages\nonebot\drivers\websockets.py", line 81, in websocket
    async with connection as ws:
  File "C:\bot\xiaoxi\.venv\lib\site-packages\websockets\legacy\client.py", line 635, in __aenter__
    return await self
  File "C:\bot\xiaoxi\.venv\lib\site-packages\websockets\legacy\client.py", line 654, in __await_impl__
    _transport, protocol = await self._create_connection()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1120, in _create_connection_transport
    await waiter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)
```

**Comment by yanyongyu** [comment]
这问题和系统有关，目前只有在老一点的windows服务器上出现，目前还不清楚怎么解决，可以尝试把qq的证书添加到系统信任证书里看看能不能解决

**Comment by chinatsu-yan** [comment]
这个问题太奇怪了，我的服务器使用的操作系统是Windows Server 2022 数据中心版，也不算老吧。反复重装了2022和2019版本都有这个问题，最后看到一个Windows Server 2022 数据中心版 64位中文UEFI版，安装之后竟然就没有这样的问题了，也不清楚是不是真的因为这个系统解决的
