### ISSUE TITLE
webhook使用问题

### ISSUE THREAD

**Issue by OverSky-gtq** [nonebot/adapter-qq#137]
```env
DRIVER=~fastapi+~httpx+~websockets
```

已经在官方控制台配置了回调地址，测试"签到"指令时报错：
```python
12-18 18:01:03 [DEBUG] nonebot | QQ | Bot 102498345 calling API post_group_messages
12-18 18:01:03 [INFO] nonebot | Matcher(type='message', module=src.plugins.thewest.handlers.activity, lineno=15) running complete
12-18 18:01:03 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.thewest.handlers.activity, lineno=15) failed.
Traceback (most recent call last):
  File "/home/ubuntu/game/bot.py", line 17, in <module>
    nonebot.run()
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 188, in run
    uvicorn.run(
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/utils.py", line 254, in run_coro_with_shield
    return await coro
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 837, in simple_run
    await handler(
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/ubuntu/game/src/plugins/thewest/handlers/activity.py", line 40, in handle_sign_in
    await sign_in.finish(f"今日已签到，下次签到时间：{hours}小时{minutes}分钟后")
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 584, in finish
    await cls.send(message, **kwargs)
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 568, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/bot.py", line 501, in send
    return await self.send_to_group(
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/bot.py", line 461, in send_to_group
    return await self.post_group_messages(
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 176, in call_api
    raise exception
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 128, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/adapter.py", line 604, in _call_api
    return await api_handler(bot, **data)
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/utils.py", line 54, in __call__
    return await self.func(inst, *args, **kwds)
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/bot.py", line 1788, in post_group_messages
    PostGroupMessagesReturn, await self._request(request)
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/bot.py", line 557, in _request
    request.headers.update(await self.get_authorization_header())
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/bot.py", line 267, in get_authorization_header
    "Authorization": await self._get_authorization_header(),
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/bot.py", line 262, in _get_authorization_header
    return f"QQBot {await self.get_access_token()}"
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/bot.py", line 247, in get_access_token
    resp = await self.adapter.request(request)
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/adapter.py", line 92, in request
    return await self.driver.request(setup)
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/drivers/httpx.py", line 129, in request
    async with self.get_session(
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/internal/driver/abstract.py", line 269, in __aenter__
    await self.setup()
  File "/home/ubuntu/game/.venv/lib/python3.10/site-packages/nonebot/drivers/httpx.py", line 100, in setup
    self._client = httpx.AsyncClient(
TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'
```

**Comment by he0119** [comment]
https://github.com/nonebot/nonebot2/issues/3149

这是 httpx 新版导致的问题，你可以选择使用 nonebot2 主分支或者降低 httpx 版本。

**Comment by zlqd123** [comment]
您好，请问下webhook回调地址是怎么连上的，我这边一直出现[](https://github.com/nonebot/adapter-qq/issues/136#issuecomment-2530357160)一样的问题，ssl证书没问题，nginx重定向和反代都不行，到最后nb里面还是http，没法用https访问

**Comment by he0119** [comment]
如果是一样的 `TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'` 的问题，请升级 nb 版本或者降级 httpx 版本。
