### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by jiangyin14** [nonebot/adapter-qq#58]
'''

  Attempting uninstall: nonebot2
    Found existing installation: nonebot2 2.0.0
    Uninstalling nonebot2-2.0.0:
      Successfully uninstalled nonebot2-2.0.0
Successfully installed nonebot-adapter-qq-1.0.0 nonebot2-2.1.1 typing-extensions-4.8.0
WARNING: You are using pip version 20.2.3; however, version 23.2.1 is available.
You should consider upgrading via the '/usr/local/py/bin/python3.8 -m pip install --upgrade pip' command.
[root@RainYun-H6oVCZwf Chiyuki-Bot]# py bot.py
10-03 18:20:19 [SUCCESS] nonebot | NoneBot is initializing...
10-03 18:20:19 [INFO] nonebot | Current Env: prod
Traceback (most recent call last):
  File "bot.py", line 21, in <module>
    app = nonebot.get_asgi()
  File "/usr/local/py/lib/python3.8/site-packages/nonebot/__init__.py", line 190, in get_asgi
    assert isinstance(
AssertionError: asgi object is only available for asgi driver
'''

**Comment by yanyongyu** [comment]
asgi对象只有在asgi类型驱动器可用，请检查你的driver配置，添加asgi驱动器或者修改bot.py删除asgi相关代码

**Comment by jiangyin14** [comment]
> asgi对象只有在asgi类型驱动器可用，请检查你的driver配置，添加asgi驱动器或者修改bot.py删除asgi相关代码

谢谢，我不是很熟悉nonebot，最近在学习，我在尝试让一个在gocq上跑的机器人在频道上跑
