### ISSUE TITLE
Bot无法启动

### ISSUE THREAD

**Issue by LsrlYrsc** [nonebot/adapter-qq#61]
在最下面加载消息之后不再加载消息，导致无法启动

```
Microsoft Windows [版本 10.0.20348.1366]
(c) Microsoft Corporation。保留所有权利。

C:\Users\Lsrl>cd nb

C:\Users\Lsrl\nb>nb run
使用 Python: C:\Users\Lsrl\nb\.venv\Scripts\python.exe
10-08 21:25:36 [SUCCESS] nonebot | NoneBot is initializing...
10-08 21:25:36 [INFO] nonebot | Current Env: prod
10-08 21:25:36 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
10-08 21:25:37 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_picmcstat"
10-08 21:25:37 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
10-08 21:25:37 [INFO] nonebot_plugin_admin | 已检测到软依赖nonebot_plugin_apscheduler, 开启定时任务功能
10-08 21:25:38 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_admin"
10-08 21:25:38 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alias"
10-08 21:25:38 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_crazy_thursday"
C:\Users\Lsrl\nb\.venv\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
10-08 21:25:38 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_PicMenu"
10-08 21:25:38 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_russian"
10-08 21:25:39 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_localstore"
10-08 21:25:41 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_memes"
10-08 21:25:41 [INFO] nonebot_plugin_steam_game_status | steam_web_key 读取成功
10-08 21:25:41 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_steam_game_status"
10-08 21:25:42 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_datastore"
10-08 21:25:42 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_chatrecorder"
10-08 21:25:42 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_wordcloud"
10-08 21:25:42 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_who_at_me"
10-08 21:25:42 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_follow_withdraw"
10-08 21:25:42 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_picstatus"
10-08 21:25:43 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_htmlrender"
10-08 21:25:43 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_bawiki"
10-08 21:25:43 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_guild_patch"
10-08 21:25:43 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_dialectlist"
10-08 21:25:43 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
10-08 21:25:43 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_saa"
10-08 21:25:43 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_capoo"
10-08 21:25:43 [SUCCESS] nonebot | Running NoneBot...
10-08 21:25:43 [INFO] nonebot_plugin_apscheduler | Scheduler Started
10-08 21:25:47 [WARNING] nonebot_plugin_crazy_thursday | Abort downloading
10-08 21:25:47 [INFO] nonebot_plugin_memes | 正在检查资源文件...
10-08 21:25:47 [INFO] nonebot_plugin_datastore | 数据库初始化完成
10-08 21:25:48 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动
10-08 21:25:48 [INFO] nonebot_plugin_htmlrender | Browser Started.
10-08 21:25:48 [INFO] nonebot_plugin_capoo | 配置项未选择本地存储图片，将通过url发送图片
10-08 21:25:48 [INFO] nonebot | Application startup completed.

```

**Comment by LsrlYrsc** [comment]
env配置文件

```
DRIVER=~fastapi
DRIVER=~httpx+~websockets
DRIVER=~aiohttp
QQGUILD_IS_SANDBOX=true
QQ_BOTS='
[
  {
    "id": "XXX",
    "token": "XXX",
    "secret": "XXX",
    "intent": {
      "guild_messages": true,
      "at_messages": false
    }
  }
]
'
HOST=127.0.0.1
PORT=2000
SUPERUSERS=["XXX"]
NICKNAME=["XXX"]
COMMAND_START=["/", "","*"]
send_group_id = ["XXX"]
CRAZY_AUTO_UPDATE=true
#LOG_LEVEL=TRACE
MCSTAT_SHOW_MODS=true
steam_web_key=XXX
```

敏感内容使用XXX代替

**Comment by LsrlYrsc** [comment]
报错更新

```
Microsoft Windows [版本 10.0.20348.1366]
(c) Microsoft Corporation。保留所有权利。

C:\Users\Lsrl>cd nb

C:\Users\Lsrl\nb>nb
使用 Python: C:\Users\Lsrl\nb\.venv\Scripts\python.exe
d8b   db  .d88b.  d8b   db d88888b d8888b.  .d88b.  d888888b
888o  88 .8P  Y8. 888o  88 88'     88  `8D .8P  Y8. `~~88~~'
88V8o 88 88    88 88V8o 88 88ooooo 88oooY' 88    88    88
88 V8o88 88    88 88 V8o88 88~~~~~ 88~~~b. 88    88    88
88  V888 `8b  d8' 88  V888 88.     88   8D `8b  d8'    88
VP   V8P  `Y88P'  VP   V8P Y88888P Y8888P'  `Y88P'     YP


欢迎使用 NoneBot CLI!
[?] 你想要进行什么操作? 管理 bot 驱动器.
[?] 你想要进行什么操作? 安装驱动器到当前项目.
[?] 想要安装的驱动器名称: websockets
Requirement already satisfied: nonebot2[websockets] in c:\users\lsrl\nb\.venv\lib\site-packages (2.1.1)
Requirement already satisfied: loguru<1.0.0,>=0.6.0 in c:\users\lsrl\nb\.venv\lib\site-packages (from nonebot2[websockets]) (0.6.0)
Requirement already satisfied: pygtrie<3.0.0,>=2.4.1 in c:\users\lsrl\nb\.venv\lib\site-packages (from nonebot2[websockets]) (2.5.0)
Requirement already satisfied: pydantic[dotenv]<2.0.0,>=1.10.0 in c:\users\lsrl\nb\.venv\lib\site-packages (from nonebot2[websockets]) (1.10.12)
Requirement already satisfied: tomli<3.0.0,>=2.0.1 in c:\users\lsrl\nb\.venv\lib\site-packages (from nonebot2[websockets]) (2.0.1)
Requirement already satisfied: yarl<2.0.0,>=1.7.2 in c:\users\lsrl\nb\.venv\lib\site-packages (from nonebot2[websockets]) (1.9.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in c:\users\lsrl\nb\.venv\lib\site-packages (from nonebot2[websockets]) (4.7.1)
Requirement already satisfied: websockets>=10.0 in c:\users\lsrl\nb\.venv\lib\site-packages (from nonebot2[websockets]) (10.4)
Requirement already satisfied: colorama>=0.3.4 in c:\users\lsrl\nb\.venv\lib\site-packages (from loguru<1.0.0,>=0.6.0->nonebot2[websockets]) (0.4.6)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\lsrl\nb\.venv\lib\site-packages (from loguru<1.0.0,>=0.6.0->nonebot2[websockets]) (1.1.0)
Requirement already satisfied: python-dotenv>=0.10.4 in c:\users\lsrl\nb\.venv\lib\site-packages (from pydantic[dotenv]<2.0.0,>=1.10.0->nonebot2[websockets]) (1.0.0)
Requirement already satisfied: multidict>=4.0 in c:\users\lsrl\nb\.venv\lib\site-packages (from yarl<2.0.0,>=1.7.2->nonebot2[websockets]) (6.0.4)
Requirement already satisfied: idna>=2.0 in c:\users\lsrl\nb\.venv\lib\site-packages (from yarl<2.0.0,>=1.7.2->nonebot2[websockets]) (3.4)

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: C:\Users\Lsrl\nb\.venv\Scripts\python.exe -m pip install --upgrade pip

C:\Users\Lsrl\nb>nb run
使用 Python: C:\Users\Lsrl\nb\.venv\Scripts\python.exe
10-08 21:35:08 [SUCCESS] nonebot | NoneBot is initializing...
10-08 21:35:08 [INFO] nonebot | Current Env: prod
10-08 21:35:08 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
10-08 21:35:08 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
10-08 21:35:09 [INFO] nonebot_plugin_admin | 已检测到软依赖nonebot_plugin_apscheduler, 开启定时任务功能
10-08 21:35:10 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_admin"
10-08 21:35:10 [INFO] nonebot_plugin_steam_game_status | steam_web_key 读取成功
10-08 21:35:10 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_steam_game_status"
10-08 21:35:10 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_saa"
10-08 21:35:10 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_localstore"
10-08 21:35:10 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_datastore"
10-08 21:35:10 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_follow_withdraw"
10-08 21:35:10 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_chatrecorder"
10-08 21:35:11 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_wordcloud"
10-08 21:35:11 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_who_at_me"
10-08 21:35:11 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_guild_patch"
10-08 21:35:11 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_dialectlist"
10-08 21:35:11 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alias"
C:\Users\Lsrl\nb\.venv\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
10-08 21:35:11 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_PicMenu"
10-08 21:35:15 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_memes"
10-08 21:35:15 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_russian"
10-08 21:35:15 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_picmcstat"
10-08 21:35:15 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_htmlrender"
10-08 21:35:16 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_bawiki"
10-08 21:35:16 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_crazy_thursday"
10-08 21:35:16 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_capoo"
10-08 21:35:16 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_picstatus"
10-08 21:35:16 [SUCCESS] nonebot | Running NoneBot...
10-08 21:35:16 [INFO] nonebot_plugin_apscheduler | Scheduler Started
10-08 21:35:16 [INFO] nonebot_plugin_datastore | 数据库初始化完成
10-08 21:35:16 [INFO] nonebot_plugin_memes | 正在检查资源文件...
10-08 21:35:17 [INFO] nonebot | QQ Guild | Bot 102070716 connected
10-08 21:35:17 [SUCCESS] nonebot | QQ 102070716 | [READY]: {'version': 1, 'session_id': 'a1b8c4f6-ed38-4efa-825a-a8b900b08ca6', 'user': {'id': '11459007399785678902', 'username': '筱桃LeiSureLy-测试中', 'avatar': None, 'bot': True, 'union_openid': None, 'union_user_account': None}, 'shard': (0, 1)}
10-08 21:35:17 [INFO] nonebot_plugin_admin | Admin 插件 初始化检测完成
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_htmlrender 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_wordcloud 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_picstatus 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_capoo 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_PicMenu 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_admin 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_who_at_me 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_saa 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_bawiki 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_datastore 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_follow_withdraw 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_picmcstat 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_memes 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_crazy_thursday 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_chatrecorder 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_alias 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_steam_game_status 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | echo 菜单数据已加载 (from code)
10-08 21:35:17 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_localstore 菜单数据已加载 (from code)
10-08 21:35:17 [ERROR] nonebot | Error when running WebSocketConnection hook. Running cancelled!
Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "C:\Users\Lsrl\nb\.venv\lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Lsrl\nb\.venv\lib\site-packages\nonebot\drivers\none.py", line 70, in run
    loop.run_until_complete(self._serve())
  File "C:\Users\Lsrl\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Lsrl\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Lsrl\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Lsrl\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Lsrl\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Lsrl\nb\.venv\lib\site-packages\nonebot\internal\driver\abstract.py", line 156, in _run_hook
    await asyncio.gather(*coros)
  File "C:\Users\Lsrl\nb\.venv\lib\site-packages\nonebot\utils.py", line 187, in run_coro_with_catch
    return await coro
  File "C:\Users\Lsrl\nb\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Lsrl\nb\.venv\lib\site-packages\nonebot_plugin_admin\__init__.py", line 45, in _
    await switcher_integrity_check(bot)
  File "C:\Users\Lsrl\nb\.venv\lib\site-packages\nonebot_plugin_admin\switcher.py", line 99, in switcher_integrity_check
    g_list = (await bot.get_group_list())
  File "C:\Users\Lsrl\nb\.venv\lib\site-packages\nonebot\adapters\qq\bot.py", line 186, in __getattr__
    raise AttributeError(
AttributeError: "Bot" object has no attribute "get_group_list"
10-08 21:35:17 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动
10-08 21:35:17 [INFO] nonebot_plugin_htmlrender | Browser Started.
10-08 21:35:24 [WARNING] nonebot_plugin_crazy_thursday | Abort downloading
10-08 21:35:24 [INFO] nonebot_plugin_capoo | 配置项未选择本地存储图片，将通过url发送图片
10-08 21:35:24 [INFO] nonebot | Application startup completed.
```

**Comment by LsrlYrsc** [comment]
pyproject.toml

```
[project]
name = "nb"
version = "0.1.0"
description = "nb"
readme = "README.md"
requires-python = ">=3.8, <4.0"

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
    {name = "QQ", module_name = "nonebot.adapters.qq"},
    {name = "QQ 频道", module_name = "nonebot.adapters.qqguild"},
]
plugins = [
    "nonebot_plugin_apscheduler",
    "nonebot_plugin_wordcloud",
    "nonebot_plugin_picstatus",
    "nonebot_plugin_who_at_me",
    "nonebot_plugin_crazy_thursday",
    "nonebot_plugin_memes",
    "nonebot_plugin_russian",
    "nonebot_plugin_dialectlist",
    "nonebot_plugin_saa",
    "nonebot_plugin_picmcstat",
    "nonebot_plugin_admin",
    "nonebot_plugin_follow_withdraw",
    "nonebot_plugin_PicMenu",
    "nonebot_plugin_bawiki",
    "nonebot_plugin_capoo",
    "nonebot_plugin_alias",
    "nonebot_plugin_steam_game_status",
]
plugin_dirs = []
builtin_plugins = ["echo"]
```

**Comment by LsrlYrsc** [comment]
为什么他默认下载的是qqguild驱动啊....
我还是重新创建一个bot算了
