### ISSUE TITLE
无法转换频道私聊信息为一个Event

### ISSUE THREAD

**Issue by kzheart** [nonebot/adapter-qq#67]
```
10-21 18:02:08 [WARNING] nonebot | QQ Guild | Failed to parse event Dispatch(opcode=<Opcode.DISPATCH: 0>, data={'author': {'avatar': 'https://qqchannel-profile-1251316161.file.myqcloud.com/16533256150e7147ab420eceb66?t=1653325650', 'id': '16362846582326858170', 'username': 'kkkkkk'}, 'channel_id': '210451697880338', 'content': 'q', 'direct_message': True, 'guild_id': '13595572922435876753', 'id': '0891efd6fda5b1cbd6bc0110929ac7d5f9ec2f3804489fc3cea906', 'member': {'joined_at': '2023-10-21T17:25:38+08:00'}, 'seq': 4, 'seq_in_channel': '4', 'src_guild_id': '7088881514225344423', 'timestamp': '2023-10-21T18:02:07+08:00'}, sequence=5, type='DIRECT_MESSAGE_CREATE', id='DIRECT_MESSAGE_CREATE:0891efd6fda5b1cbd6bc0110929ac7d5f9ec2f3804489fc3cea906')
Traceback (most recent call last):
  File "D:\code\py\bot\bot.py", line 18, in <module>
    nonebot.run()
  File "C:\Users\A\.conda\envs\botenv\lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\A\.conda\envs\botenv\lib\site-packages\nonebot\drivers\none.py", line 70, in run
    loop.run_until_complete(self._serve())
  File "C:\Users\A\.conda\envs\botenv\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\A\.conda\envs\botenv\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\A\.conda\envs\botenv\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\A\.conda\envs\botenv\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\A\.conda\envs\botenv\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\A\.conda\envs\botenv\lib\site-packages\nonebot\adapters\qq\adapter.py", line 180, in _forward_ws
    await self._loop(bot, ws)
> File "C:\Users\A\.conda\envs\botenv\lib\site-packages\nonebot\adapters\qq\adapter.py", line 344, in _loop
    event = self.payload_to_event(payload)
  File "C:\Users\A\.conda\envs\botenv\lib\site-packages\nonebot\adapters\qq\adapter.py", line 407, in payload_to_event
    return EventClass.parse_obj(payload.data)
  File "pydantic\main.py", line 526, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DirectMessageCreateEvent
member -> roles
  field required (type=value_error.missing)
```

配置如下:
DRIVER=~fastapi+~websockets+~httpx
DRIVER=~aiohttp
QQ_IS_SANDBOX=false
QQ_BOTS='
[
  {
    "id": "?",
    "token": "?",
    "secret": "?",
    "intent": {
      "guild_messages": true,
      "at_messages": false,
      "direct_message": true
    }
  }
]
'

**Comment by yanyongyu** [comment]
already fixed in #66
