### ISSUE TITLE
无法登录到群Bot

### ISSUE THREAD

**Issue by XTxiaoting14332** [nonebot/adapter-qq#72]
安装adapter-qq后运行nb run显示如下内容：
<code>11-10 05:18:32 [DEBUG] nonebot | Succeeded to load adapter "QQ"
11-10 05:18:32 [DEBUG] nonebot | Succeeded to load adapter "Minecraft"
11-10 05:18:32 [SUCCESS] nonebot | Succeeded to load plugin "uniseg" from "nonebot_plugin_alconna.uniseg"
11-10 05:18:32 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
11-10 05:18:33 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_status"
11-10 05:18:33 [SUCCESS] nonebot | Running NoneBot...
11-10 05:18:33 [DEBUG] nonebot | Loaded adapters: QQ, Minecraft
11-10 05:18:34 [INFO] uvicorn | Started server process [837869]
11-10 05:18:34 [INFO] uvicorn | Waiting for application startup.
11-10 05:18:34 [DEBUG] nonebot | QQ Guild | QQ run in sandbox mode: True
11-10 05:18:34 [DEBUG] nonebot | QQ Guild | QQ api base url: https://sandbox.api.sgroup.qq.com
11-10 05:18:34 [DEBUG] nonebot | QQ Guild | Bot 3889000112 calling API shard_url_get
11-10 05:18:34 [INFO] uvicorn | Application startup complete.
11-10 05:18:34 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
11-10 05:18:34 [ERROR] nonebot | QQ Guild | Failed to get gateway info.
Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "/home/bot/xt/rootfs/home/NightWind-qq/.venv/lib/python3.8/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "/home/bot/xt/rootfs/home/NightWind-qq/.venv/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 201, in run
    uvicorn.run(
  File "/home/bot/xt/rootfs/home/NightWind-qq/.venv/lib/python3.8/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/home/bot/xt/rootfs/home/NightWind-qq/.venv/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/home/bot/xt/rootfs/home/NightWind-qq/.venv/lib/python3.8/site-packages/nonebot/adapters/qq/adapter.py", line 105, in run_bot
    gateway_info = await bot.shard_url_get()
  File "/home/bot/xt/rootfs/home/NightWind-qq/.venv/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 123, in call_api
    raise exception
  File "/home/bot/xt/rootfs/home/NightWind-qq/.venv/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/home/bot/xt/rootfs/home/NightWind-qq/.venv/lib/python3.8/site-packages/nonebot/adapters/qq/adapter.py", line 415, in _call_api
    return await api_handler(bot, **data)
  File "/home/bot/xt/rootfs/home/NightWind-qq/.venv/lib/python3.8/site-packages/nonebot/adapters/qq/utils.py", line 64, in __call__
    return await self.func(inst, *args, **kwds)
  File "/home/bot/xt/rootfs/home/NightWind-qq/.venv/lib/python3.8/site-packages/nonebot/adapters/qq/bot.py", line 1508, in shard_url_get
    return parse_obj_as(ShardUrlGetReturn, await self._request(request))
  File "/home/bot/xt/rootfs/home/NightWind-qq/.venv/lib/python3.8/site-packages/nonebot/adapters/qq/bot.py", line 459, in _request
    request.headers.update(await self.get_authorization_header())
  File "/home/bot/xt/rootfs/home/NightWind-qq/.venv/lib/python3.8/site-packages/nonebot/adapters/qq/bot.py", line 266, in get_authorization_header
    headers = {"Authorization": await self._get_authorization_header()}
  File "/home/bot/xt/rootfs/home/NightWind-qq/.venv/lib/python3.8/site-packages/nonebot/adapters/qq/bot.py", line 261, in _get_authorization_header
    return f"QQBot {await self.get_access_token()}"
  File "/home/bot/xt/rootfs/home/NightWind-qq/.venv/lib/python3.8/site-packages/nonebot/adapters/qq/bot.py", line 252, in get_access_token
    self._access_token = cast(str, data["access_token"])
KeyError: 'access_token'</code>

.env文件如下:
<code>
NVIRONMENT=dev
DRIVER=~fastapi+~httpx+~websockets+~aiohttp

QQ_BOTS='
[
  {
    "id": "3xxxxxxxx2",
    "token": "mxxxxxxxxxxxxxxxxxxxDu",
    "secret": "zxxxxxxxxxxxxxx8J",
    "intent": {
      "c2c_group_at_messages": true
    }
  }
]
'
</code>

**Comment by yanyongyu** [comment]
你开通群bot权限了吗

**Comment by XTxiaoting14332** [comment]
> 你开通群bot权限了吗

开通了
uin啥的都拿到了

**Comment by yanyongyu** [comment]
我是指你开通群权限了吗，请看你的机器人控制台是否有群设置

**Comment by XTxiaoting14332** [comment]
> 我是指你开通群权限了吗，请看你的机器人控制台是否有群设置

还没有 那没事了（）
